version: '3.9'

services:
  api:
    image: api:latest
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - mongo

  app:
    image: app:latest
    build: ./app
    ports:
      - 5173:5173
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db